// VDEMPCController.h
// Generated by VDE Phase 2 UE5 Integration
// 2026-02-06T23:21:45.365378

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "VDETypes.h"
#include "VDEMPCController.generated.h"

class UMaterialParameterCollection;
class UMaterialParameterCollectionInstance;

/**
 * Controller that manages VDE Material Parameter Collection.
 * 
 * Place one in the level to automatically update material parameters
 * based on VDE state. All materials using the VDE MPC will update.
 */
UCLASS()
class VDE_API AVDEMPCController : public AActor
{
    GENERATED_BODY()

public:
    AVDEMPCController();

    virtual void BeginPlay() override;
    virtual void Tick(float DeltaTime) override;

    /** Manual update */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void UpdateMaterialParameters(const FVDEMaterialParameters& Parameters);

    /** The Material Parameter Collection to update */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE")
    UMaterialParameterCollection* VDEParameterCollection;

    /** Interpolation speed */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE", meta = (ClampMin = "0.1", ClampMax = "10.0"))
    float InterpolationSpeed = 2.0f;

    /** Auto-update from subsystem */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE")
    bool bAutoUpdate = true;

protected:
    /** Runtime instance of the MPC */
    UPROPERTY()
    UMaterialParameterCollectionInstance* MPCInstance;

    /** Current parameters */
    FVDEMaterialParameters CurrentParameters;

    /** Target parameters */
    FVDEMaterialParameters TargetParameters;

    /** Set a scalar parameter on the MPC */
    void SetScalarParameter(FName ParameterName, float Value);

    /** Set a vector parameter on the MPC */
    void SetVectorParameter(FName ParameterName, FLinearColor Value);

    /** Apply all parameters */
    void ApplyParameters();

    /** Interpolate parameters */
    void InterpolateParameters(float DeltaTime);
};
