// VDEPostProcessComponent.h
// Generated by VDE Phase 2 UE5 Integration
// 2026-02-06T23:21:45.365375

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "VDETypes.h"
#include "VDEPostProcessComponent.generated.h"

class UPostProcessComponent;

/**
 * Component that automatically applies VDE post-process settings.
 * 
 * Attach to a Post Process Volume or the player camera.
 * It will automatically update post-process settings based on VDE state.
 */
UCLASS(ClassGroup=(VDE), meta=(BlueprintSpawnableComponent))
class VDE_API UVDEPostProcessComponent : public UActorComponent
{
    GENERATED_BODY()

public:
    UVDEPostProcessComponent();

    virtual void BeginPlay() override;
    virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

    /** Manual update (call if not using tick) */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void UpdatePostProcessSettings(const FVDEPostProcessSettings& Settings);

    /** Interpolation speed for smooth transitions */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE", meta = (ClampMin = "0.1", ClampMax = "10.0"))
    float InterpolationSpeed = 2.0f;

    /** Whether to automatically update from VDE subsystem */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE")
    bool bAutoUpdate = true;

protected:
    /** Cached reference to post process component */
    UPROPERTY()
    UPostProcessComponent* PostProcessComponent;

    /** Current interpolated settings */
    FVDEPostProcessSettings CurrentSettings;

    /** Target settings */
    FVDEPostProcessSettings TargetSettings;

    /** Apply settings to the post process component */
    void ApplySettings();

    /** Interpolate between current and target */
    void InterpolateSettings(float DeltaTime);
};
