// VDESubsystem.h
// Generated by VDE Phase 2 UE5 Integration
// 2026-02-06T23:21:45.365368

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "VDETypes.h"
#include "VDESubsystem.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnVDERegionStateChanged, const FVDERegionState&, NewState);

/**
 * VDE Subsystem - Manages Visual Discomfort Engine state.
 * 
 * This subsystem receives VDE data from the server/simulation and
 * distributes it to relevant systems (post-process, materials, spawners).
 */
UCLASS()
class VDE_API UVDESubsystem : public UGameInstanceSubsystem
{
    GENERATED_BODY()

public:
    /** Initialize the subsystem */
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;

    /** Clean up */
    virtual void Deinitialize() override;

    // =========================================================================
    // Region Management
    // =========================================================================

    /** Update state for a specific region */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void UpdateRegionState(const FVDERegionState& NewState);

    /** Get current state for a region */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    bool GetRegionState(const FString& RegionID, FVDERegionState& OutState) const;

    /** Get the region the player is currently in */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    FString GetCurrentRegionID() const;

    /** Set the current region (call when player moves between regions) */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void SetCurrentRegion(const FString& RegionID);

    // =========================================================================
    // Parameter Access
    // =========================================================================

    /** Get post-process settings for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|PostProcess")
    FVDEPostProcessSettings GetCurrentPostProcessSettings() const;

    /** Get material parameters for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Materials")
    FVDEMaterialParameters GetCurrentMaterialParameters() const;

    /** Get Niagara parameters for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Particles")
    FVDENiagaraParameters GetCurrentNiagaraParameters() const;

    /** Get spawn settings for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Spawning")
    FVDESpawnSettings GetCurrentSpawnSettings() const;

    /** Get attraction settings for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Attraction")
    FVDEAttractionSettings GetCurrentAttractionSettings() const;

    // =========================================================================
    // Convenience Accessors
    // =========================================================================

    /** Get current VDI for the player's region */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    float GetCurrentVDI() const;

    /** Get current visual phase */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    EVDEVisualPhase GetCurrentPhase() const;

    /** Get current wildlife state */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    EVDEWildlifeState GetCurrentWildlifeState() const;

    /** Check if current region is attracting players */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    bool IsCurrentRegionAttracting() const;

    // =========================================================================
    // Events
    // =========================================================================

    /** Broadcast when any region's state changes */
    UPROPERTY(BlueprintAssignable, Category = "VDE|Events")
    FOnVDERegionStateChanged OnRegionStateChanged;

protected:
    /** Map of region ID to state */
    UPROPERTY()
    TMap<FString, FVDERegionState> RegionStates;

    /** Currently active region ID */
    UPROPERTY()
    FString CurrentRegionID;

    /** Apply settings to subsystems when region changes */
    void ApplyCurrentRegionSettings();
};
