// VDETypes.h
// Generated by VDE Phase 2 UE5 Integration
// 2026-02-06T23:21:45.365347

#pragma once

#include "CoreMinimal.h"
#include "VDETypes.generated.h"

/**
 * Visual pressure phases based on population density.
 */
UENUM(BlueprintType)
enum class EVDEVisualPhase : uint8
{
    Pristine    UMETA(DisplayName = "Pristine"),      // 0-10%: Maximum comfort
    Healthy     UMETA(DisplayName = "Healthy"),       // 10-20%: Natural state
    Occupied    UMETA(DisplayName = "Occupied"),      // 20-35%: Subtle wear begins
    Busy        UMETA(DisplayName = "Busy"),          // 35-50%: Motion irregularity
    Crowded     UMETA(DisplayName = "Crowded"),       // 50-70%: Clear fatigue
    Saturated   UMETA(DisplayName = "Saturated")      // 70%+: Maximum pressure
};

/**
 * Wildlife behavior states.
 */
UENUM(BlueprintType)
enum class EVDEWildlifeState : uint8
{
    Thriving    UMETA(DisplayName = "Thriving"),      // Full activity
    Wary        UMETA(DisplayName = "Wary"),          // Reduced, cautious
    Retreating  UMETA(DisplayName = "Retreating"),    // Edge only
    Absent      UMETA(DisplayName = "Absent")         // Gone
};

/**
 * Post-process settings for VDE.
 * Applied as modifiers to base post-process values.
 */
USTRUCT(BlueprintType)
struct FVDEPostProcessSettings
{
    GENERATED_BODY()

    /** Multiplier for bloom intensity (1.0 = base, >1.0 = more bloom) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bloom")
    float BloomIntensityMultiplier = 1.0f;

    /** Bias for bloom threshold (negative = lower threshold = more bloom) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bloom")
    float BloomThresholdBias = 0.0f;

    /** Saturation multiplier (0.95-1.0 for subtle effect) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Color", meta = (ClampMin = "0.9", ClampMax = "1.1"))
    float SaturationMultiplier = 1.0f;

    /** Contrast multiplier (reduce for flatter look) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Color", meta = (ClampMin = "0.7", ClampMax = "1.3"))
    float ContrastMultiplier = 1.0f;

    /** Color temperature offset in Kelvin */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Color")
    float ColorTempOffset = 0.0f;

    /** Shadow amount multiplier (reduce for softer shadows) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Shadows", meta = (ClampMin = "0.5", ClampMax = "1.5"))
    float ShadowAmountMultiplier = 1.0f;

    /** Fog density multiplier */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
    float FogDensityMultiplier = 1.0f;

    /** Fog height falloff multiplier */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
    float FogHeightFalloffMultiplier = 1.0f;

    /** Vignette intensity (0.0-0.4 range) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Vignette", meta = (ClampMin = "0.0", ClampMax = "0.5"))
    float VignetteIntensity = 0.0f;
};

/**
 * Material parameter collection values for VDE.
 * Applied to scene materials via MPC.
 */
USTRUCT(BlueprintType)
struct FVDEMaterialParameters
{
    GENERATED_BODY()

    // Foliage
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliageWindIntensity = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliageWindTurbulence = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliagePhaseOffsetRange = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliageColorDesaturation = 0.0f;

    // Water
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Water", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float WaterClarity = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Water")
    float WaterTurbulence = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Water")
    FLinearColor WaterColorTint = FLinearColor::White;

    // Ground
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ground", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float GroundWearIntensity = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ground", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float GroundDisplacementReduction = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ground")
    float GroundColorDarkening = 0.0f;

    // Cloth
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cloth")
    float ClothDampingMultiplier = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cloth")
    float ClothWindResponse = 1.0f;

    // Props
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Props")
    float PropJitterIntensity = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Props")
    float PropJitterFrequency = 0.0f;
};

/**
 * Niagara particle system parameters.
 */
USTRUCT(BlueprintType)
struct FVDENiagaraParameters
{
    GENERATED_BODY()

    // Dust
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    float DustSpawnRate = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    float DustLifetime = 3.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    FVector2D DustSizeRange = FVector2D(0.5f, 2.0f);

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    float DustVelocityScale = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    FLinearColor DustColorTint = FLinearColor(0.8f, 0.75f, 0.7f, 0.3f);

    // Pollen
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pollen")
    float PollenSpawnRate = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pollen")
    float PollenDriftSpeed = 0.5f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pollen")
    float PollenSize = 0.3f;

    // Debris
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Debris")
    float DebrisSpawnRate = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Debris")
    float DebrisFallSpeed = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Debris")
    float DebrisRotationSpeed = 1.0f;

    // Wind
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
    FVector WindDirection = FVector(1.0f, 0.0f, 0.0f);

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
    float WindDirectionVariance = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
    float GlobalVelocityScale = 1.0f;

    // Insects
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insects")
    float InsectDensity = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insects")
    float InsectActivityLevel = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insects")
    float InsectAvoidanceRadius = 100.0f;
};

/**
 * Spawn settings for wildlife and NPCs.
 */
USTRUCT(BlueprintType)
struct FVDESpawnSettings
{
    GENERATED_BODY()

    // Wildlife
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float WildlifeSpawnMultiplier = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    EVDEWildlifeState WildlifeBehaviorState = EVDEWildlifeState::Thriving;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float BirdLandingProbability = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float BirdFleeDistance = 300.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float AmbientCreatureDensity = 1.0f;

    // NPCs
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs", meta = (Bitmask, BitmaskEnum = "/Script/VDE.EVDENPCIdleBehavior"))
    int32 NPCIdleBehaviorMask = 0xFFFFFFFF;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float NPCComfortLevel = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs")
    float NPCRepositionFrequency = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs")
    float NPCInteractionRadius = 200.0f;
};

/**
 * Attraction settings for low-population areas.
 */
USTRUCT(BlueprintType)
struct FVDEAttractionSettings
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    bool bIsActive = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    float AttractionStrength = 0.0f;

    // Light
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Light")
    float LightColorWarmth = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Light")
    float GodRayIntensity = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Light")
    float AmbientLightBoost = 0.0f;

    // Visual
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Visual")
    float FogReduction = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Visual")
    float ContrastBoost = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Visual")
    float SaturationBoost = 0.0f;

    // Life
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Life")
    float WildlifeSpawnBonus = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Life")
    int32 DistantActivitySpawns = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Life")
    float AmbientSoundBonus = 0.0f;
};

/**
 * Complete VDE state for a region.
 * This is the main data structure passed from VDE to UE5.
 */
USTRUCT(BlueprintType)
struct FVDERegionState
{
    GENERATED_BODY()

    /** Unique identifier for this region */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Identity")
    FString RegionID;

    /** Current population ratio (0.0-1.0) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float Population = 0.0f;

    /** Visual Discomfort Index (-1.0 to 1.0) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
    float VDI = 0.0f;

    /** Current visual phase */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    EVDEVisualPhase Phase = EVDEVisualPhase::Pristine;

    /** Current wildlife behavior state */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    EVDEWildlifeState WildlifeState = EVDEWildlifeState::Thriving;

    /** Accumulated environmental wear (0.0-1.0) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float AccumulatedWear = 0.0f;

    /** Post-process settings */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDEPostProcessSettings PostProcess;

    /** Material parameters */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDEMaterialParameters Materials;

    /** Niagara particle parameters */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDENiagaraParameters Niagara;

    /** Spawn settings */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDESpawnSettings Spawning;

    /** Attraction settings */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDEAttractionSettings Attraction;

    /** Timestamp of this state */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Timing")
    float Timestamp = 0.0f;

    /** Time since last update */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Timing")
    float DeltaTime = 0.0f;
};
