"""
VDE Phase 2: UE5 C++ Header Generation

Generates C++ header files for Unreal Engine 5 integration.
These headers define the data structures that UE5 uses to receive
VDE parameters.

Usage:
    python -m vde.ue5_codegen --output /path/to/UE5/Source/VDE/
"""

import os
from datetime import datetime
from typing import List, Tuple


def generate_vde_types_header() -> str:
    """Generate VDETypes.h with core enums and structs."""
    return '''// VDETypes.h
// Generated by VDE Phase 2 UE5 Integration
// {timestamp}

#pragma once

#include "CoreMinimal.h"
#include "VDETypes.generated.h"

/**
 * Visual pressure phases based on population density.
 */
UENUM(BlueprintType)
enum class EVDEVisualPhase : uint8
{{
    Pristine    UMETA(DisplayName = "Pristine"),      // 0-10%: Maximum comfort
    Healthy     UMETA(DisplayName = "Healthy"),       // 10-20%: Natural state
    Occupied    UMETA(DisplayName = "Occupied"),      // 20-35%: Subtle wear begins
    Busy        UMETA(DisplayName = "Busy"),          // 35-50%: Motion irregularity
    Crowded     UMETA(DisplayName = "Crowded"),       // 50-70%: Clear fatigue
    Saturated   UMETA(DisplayName = "Saturated")      // 70%+: Maximum pressure
}};

/**
 * Wildlife behavior states.
 */
UENUM(BlueprintType)
enum class EVDEWildlifeState : uint8
{{
    Thriving    UMETA(DisplayName = "Thriving"),      // Full activity
    Wary        UMETA(DisplayName = "Wary"),          // Reduced, cautious
    Retreating  UMETA(DisplayName = "Retreating"),    // Edge only
    Absent      UMETA(DisplayName = "Absent")         // Gone
}};

/**
 * Post-process settings for VDE.
 * Applied as modifiers to base post-process values.
 */
USTRUCT(BlueprintType)
struct FVDEPostProcessSettings
{{
    GENERATED_BODY()

    /** Multiplier for bloom intensity (1.0 = base, >1.0 = more bloom) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bloom")
    float BloomIntensityMultiplier = 1.0f;

    /** Bias for bloom threshold (negative = lower threshold = more bloom) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Bloom")
    float BloomThresholdBias = 0.0f;

    /** Saturation multiplier (0.95-1.0 for subtle effect) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Color", meta = (ClampMin = "0.9", ClampMax = "1.1"))
    float SaturationMultiplier = 1.0f;

    /** Contrast multiplier (reduce for flatter look) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Color", meta = (ClampMin = "0.7", ClampMax = "1.3"))
    float ContrastMultiplier = 1.0f;

    /** Color temperature offset in Kelvin */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Color")
    float ColorTempOffset = 0.0f;

    /** Shadow amount multiplier (reduce for softer shadows) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Shadows", meta = (ClampMin = "0.5", ClampMax = "1.5"))
    float ShadowAmountMultiplier = 1.0f;

    /** Fog density multiplier */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
    float FogDensityMultiplier = 1.0f;

    /** Fog height falloff multiplier */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Fog")
    float FogHeightFalloffMultiplier = 1.0f;

    /** Vignette intensity (0.0-0.4 range) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Vignette", meta = (ClampMin = "0.0", ClampMax = "0.5"))
    float VignetteIntensity = 0.0f;
}};

/**
 * Material parameter collection values for VDE.
 * Applied to scene materials via MPC.
 */
USTRUCT(BlueprintType)
struct FVDEMaterialParameters
{{
    GENERATED_BODY()

    // Foliage
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliageWindIntensity = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliageWindTurbulence = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliagePhaseOffsetRange = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Foliage")
    float FoliageColorDesaturation = 0.0f;

    // Water
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Water", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float WaterClarity = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Water")
    float WaterTurbulence = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Water")
    FLinearColor WaterColorTint = FLinearColor::White;

    // Ground
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ground", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float GroundWearIntensity = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ground", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float GroundDisplacementReduction = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Ground")
    float GroundColorDarkening = 0.0f;

    // Cloth
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cloth")
    float ClothDampingMultiplier = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Cloth")
    float ClothWindResponse = 1.0f;

    // Props
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Props")
    float PropJitterIntensity = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Props")
    float PropJitterFrequency = 0.0f;
}};

/**
 * Niagara particle system parameters.
 */
USTRUCT(BlueprintType)
struct FVDENiagaraParameters
{{
    GENERATED_BODY()

    // Dust
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    float DustSpawnRate = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    float DustLifetime = 3.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    FVector2D DustSizeRange = FVector2D(0.5f, 2.0f);

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    float DustVelocityScale = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Dust")
    FLinearColor DustColorTint = FLinearColor(0.8f, 0.75f, 0.7f, 0.3f);

    // Pollen
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pollen")
    float PollenSpawnRate = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pollen")
    float PollenDriftSpeed = 0.5f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Pollen")
    float PollenSize = 0.3f;

    // Debris
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Debris")
    float DebrisSpawnRate = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Debris")
    float DebrisFallSpeed = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Debris")
    float DebrisRotationSpeed = 1.0f;

    // Wind
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
    FVector WindDirection = FVector(1.0f, 0.0f, 0.0f);

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
    float WindDirectionVariance = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wind")
    float GlobalVelocityScale = 1.0f;

    // Insects
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insects")
    float InsectDensity = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insects")
    float InsectActivityLevel = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Insects")
    float InsectAvoidanceRadius = 100.0f;
}};

/**
 * Spawn settings for wildlife and NPCs.
 */
USTRUCT(BlueprintType)
struct FVDESpawnSettings
{{
    GENERATED_BODY()

    // Wildlife
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float WildlifeSpawnMultiplier = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    EVDEWildlifeState WildlifeBehaviorState = EVDEWildlifeState::Thriving;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float BirdLandingProbability = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float BirdFleeDistance = 300.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Wildlife")
    float AmbientCreatureDensity = 1.0f;

    // NPCs
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs", meta = (Bitmask, BitmaskEnum = "/Script/VDE.EVDENPCIdleBehavior"))
    int32 NPCIdleBehaviorMask = 0xFFFFFFFF;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float NPCComfortLevel = 1.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs")
    float NPCRepositionFrequency = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "NPCs")
    float NPCInteractionRadius = 200.0f;
}};

/**
 * Attraction settings for low-population areas.
 */
USTRUCT(BlueprintType)
struct FVDEAttractionSettings
{{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    bool bIsActive = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    float AttractionStrength = 0.0f;

    // Light
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Light")
    float LightColorWarmth = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Light")
    float GodRayIntensity = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Light")
    float AmbientLightBoost = 0.0f;

    // Visual
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Visual")
    float FogReduction = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Visual")
    float ContrastBoost = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Visual")
    float SaturationBoost = 0.0f;

    // Life
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Life")
    float WildlifeSpawnBonus = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Life")
    int32 DistantActivitySpawns = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Life")
    float AmbientSoundBonus = 0.0f;
}};

/**
 * Complete VDE state for a region.
 * This is the main data structure passed from VDE to UE5.
 */
USTRUCT(BlueprintType)
struct FVDERegionState
{{
    GENERATED_BODY()

    /** Unique identifier for this region */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Identity")
    FString RegionID;

    /** Current population ratio (0.0-1.0) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float Population = 0.0f;

    /** Visual Discomfort Index (-1.0 to 1.0) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State", meta = (ClampMin = "-1.0", ClampMax = "1.0"))
    float VDI = 0.0f;

    /** Current visual phase */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    EVDEVisualPhase Phase = EVDEVisualPhase::Pristine;

    /** Current wildlife behavior state */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State")
    EVDEWildlifeState WildlifeState = EVDEWildlifeState::Thriving;

    /** Accumulated environmental wear (0.0-1.0) */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "State", meta = (ClampMin = "0.0", ClampMax = "1.0"))
    float AccumulatedWear = 0.0f;

    /** Post-process settings */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDEPostProcessSettings PostProcess;

    /** Material parameters */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDEMaterialParameters Materials;

    /** Niagara particle parameters */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDENiagaraParameters Niagara;

    /** Spawn settings */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDESpawnSettings Spawning;

    /** Attraction settings */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Parameters")
    FVDEAttractionSettings Attraction;

    /** Timestamp of this state */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Timing")
    float Timestamp = 0.0f;

    /** Time since last update */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Timing")
    float DeltaTime = 0.0f;
}};
'''.format(timestamp=datetime.now().isoformat())


def generate_vde_subsystem_header() -> str:
    """Generate VDESubsystem.h for the game instance subsystem."""
    return '''// VDESubsystem.h
// Generated by VDE Phase 2 UE5 Integration
// {timestamp}

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/GameInstanceSubsystem.h"
#include "VDETypes.h"
#include "VDESubsystem.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnVDERegionStateChanged, const FVDERegionState&, NewState);

/**
 * VDE Subsystem - Manages Visual Discomfort Engine state.
 * 
 * This subsystem receives VDE data from the server/simulation and
 * distributes it to relevant systems (post-process, materials, spawners).
 */
UCLASS()
class VDE_API UVDESubsystem : public UGameInstanceSubsystem
{{
    GENERATED_BODY()

public:
    /** Initialize the subsystem */
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;

    /** Clean up */
    virtual void Deinitialize() override;

    // =========================================================================
    // Region Management
    // =========================================================================

    /** Update state for a specific region */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void UpdateRegionState(const FVDERegionState& NewState);

    /** Get current state for a region */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    bool GetRegionState(const FString& RegionID, FVDERegionState& OutState) const;

    /** Get the region the player is currently in */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    FString GetCurrentRegionID() const;

    /** Set the current region (call when player moves between regions) */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void SetCurrentRegion(const FString& RegionID);

    // =========================================================================
    // Parameter Access
    // =========================================================================

    /** Get post-process settings for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|PostProcess")
    FVDEPostProcessSettings GetCurrentPostProcessSettings() const;

    /** Get material parameters for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Materials")
    FVDEMaterialParameters GetCurrentMaterialParameters() const;

    /** Get Niagara parameters for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Particles")
    FVDENiagaraParameters GetCurrentNiagaraParameters() const;

    /** Get spawn settings for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Spawning")
    FVDESpawnSettings GetCurrentSpawnSettings() const;

    /** Get attraction settings for current region */
    UFUNCTION(BlueprintCallable, Category = "VDE|Attraction")
    FVDEAttractionSettings GetCurrentAttractionSettings() const;

    // =========================================================================
    // Convenience Accessors
    // =========================================================================

    /** Get current VDI for the player's region */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    float GetCurrentVDI() const;

    /** Get current visual phase */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    EVDEVisualPhase GetCurrentPhase() const;

    /** Get current wildlife state */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    EVDEWildlifeState GetCurrentWildlifeState() const;

    /** Check if current region is attracting players */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    bool IsCurrentRegionAttracting() const;

    // =========================================================================
    // Events
    // =========================================================================

    /** Broadcast when any region's state changes */
    UPROPERTY(BlueprintAssignable, Category = "VDE|Events")
    FOnVDERegionStateChanged OnRegionStateChanged;

protected:
    /** Map of region ID to state */
    UPROPERTY()
    TMap<FString, FVDERegionState> RegionStates;

    /** Currently active region ID */
    UPROPERTY()
    FString CurrentRegionID;

    /** Apply settings to subsystems when region changes */
    void ApplyCurrentRegionSettings();
}};
'''.format(timestamp=datetime.now().isoformat())


def generate_vde_post_process_component_header() -> str:
    """Generate VDEPostProcessComponent.h for automatic post-process binding."""
    return '''// VDEPostProcessComponent.h
// Generated by VDE Phase 2 UE5 Integration
// {timestamp}

#pragma once

#include "CoreMinimal.h"
#include "Components/ActorComponent.h"
#include "VDETypes.h"
#include "VDEPostProcessComponent.generated.h"

class UPostProcessComponent;

/**
 * Component that automatically applies VDE post-process settings.
 * 
 * Attach to a Post Process Volume or the player camera.
 * It will automatically update post-process settings based on VDE state.
 */
UCLASS(ClassGroup=(VDE), meta=(BlueprintSpawnableComponent))
class VDE_API UVDEPostProcessComponent : public UActorComponent
{{
    GENERATED_BODY()

public:
    UVDEPostProcessComponent();

    virtual void BeginPlay() override;
    virtual void TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;

    /** Manual update (call if not using tick) */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void UpdatePostProcessSettings(const FVDEPostProcessSettings& Settings);

    /** Interpolation speed for smooth transitions */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE", meta = (ClampMin = "0.1", ClampMax = "10.0"))
    float InterpolationSpeed = 2.0f;

    /** Whether to automatically update from VDE subsystem */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE")
    bool bAutoUpdate = true;

protected:
    /** Cached reference to post process component */
    UPROPERTY()
    UPostProcessComponent* PostProcessComponent;

    /** Current interpolated settings */
    FVDEPostProcessSettings CurrentSettings;

    /** Target settings */
    FVDEPostProcessSettings TargetSettings;

    /** Apply settings to the post process component */
    void ApplySettings();

    /** Interpolate between current and target */
    void InterpolateSettings(float DeltaTime);
}};
'''.format(timestamp=datetime.now().isoformat())


def generate_vde_mpc_controller_header() -> str:
    """Generate VDEMPCController.h for Material Parameter Collection management."""
    return '''// VDEMPCController.h
// Generated by VDE Phase 2 UE5 Integration
// {timestamp}

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "VDETypes.h"
#include "VDEMPCController.generated.h"

class UMaterialParameterCollection;
class UMaterialParameterCollectionInstance;

/**
 * Controller that manages VDE Material Parameter Collection.
 * 
 * Place one in the level to automatically update material parameters
 * based on VDE state. All materials using the VDE MPC will update.
 */
UCLASS()
class VDE_API AVDEMPCController : public AActor
{{
    GENERATED_BODY()

public:
    AVDEMPCController();

    virtual void BeginPlay() override;
    virtual void Tick(float DeltaTime) override;

    /** Manual update */
    UFUNCTION(BlueprintCallable, Category = "VDE")
    void UpdateMaterialParameters(const FVDEMaterialParameters& Parameters);

    /** The Material Parameter Collection to update */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE")
    UMaterialParameterCollection* VDEParameterCollection;

    /** Interpolation speed */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE", meta = (ClampMin = "0.1", ClampMax = "10.0"))
    float InterpolationSpeed = 2.0f;

    /** Auto-update from subsystem */
    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "VDE")
    bool bAutoUpdate = true;

protected:
    /** Runtime instance of the MPC */
    UPROPERTY()
    UMaterialParameterCollectionInstance* MPCInstance;

    /** Current parameters */
    FVDEMaterialParameters CurrentParameters;

    /** Target parameters */
    FVDEMaterialParameters TargetParameters;

    /** Set a scalar parameter on the MPC */
    void SetScalarParameter(FName ParameterName, float Value);

    /** Set a vector parameter on the MPC */
    void SetVectorParameter(FName ParameterName, FLinearColor Value);

    /** Apply all parameters */
    void ApplyParameters();

    /** Interpolate parameters */
    void InterpolateParameters(float DeltaTime);
}};
'''.format(timestamp=datetime.now().isoformat())


def generate_all_headers(output_dir: str) -> List[str]:
    """Generate all UE5 header files."""
    
    files = [
        ('VDETypes.h', generate_vde_types_header()),
        ('VDESubsystem.h', generate_vde_subsystem_header()),
        ('VDEPostProcessComponent.h', generate_vde_post_process_component_header()),
        ('VDEMPCController.h', generate_vde_mpc_controller_header()),
    ]
    
    os.makedirs(output_dir, exist_ok=True)
    generated = []
    
    for filename, content in files:
        filepath = os.path.join(output_dir, filename)
        with open(filepath, 'w') as f:
            f.write(content)
        generated.append(filepath)
    
    return generated


def generate_mpc_asset_json() -> str:
    """
    Generate JSON definition for Material Parameter Collection asset.
    
    This can be imported into UE5 to create the VDE_Parameters MPC.
    """
    return '''{
  "Name": "VDE_Parameters",
  "ScalarParameters": [
    {"Name": "Foliage_WindIntensity", "DefaultValue": 1.0},
    {"Name": "Foliage_WindTurbulence", "DefaultValue": 0.0},
    {"Name": "Foliage_PhaseOffsetRange", "DefaultValue": 0.0},
    {"Name": "Foliage_ColorDesaturation", "DefaultValue": 0.0},
    {"Name": "Water_Clarity", "DefaultValue": 1.0},
    {"Name": "Water_Turbulence", "DefaultValue": 0.0},
    {"Name": "Ground_WearIntensity", "DefaultValue": 0.0},
    {"Name": "Ground_DisplacementReduction", "DefaultValue": 0.0},
    {"Name": "Ground_ColorDarkening", "DefaultValue": 0.0},
    {"Name": "Cloth_DampingMultiplier", "DefaultValue": 1.0},
    {"Name": "Cloth_WindResponse", "DefaultValue": 1.0},
    {"Name": "Prop_JitterIntensity", "DefaultValue": 0.0},
    {"Name": "Prop_JitterFrequency", "DefaultValue": 0.0},
    {"Name": "VDI_Value", "DefaultValue": 0.0},
    {"Name": "Population_Ratio", "DefaultValue": 0.0}
  ],
  "VectorParameters": [
    {"Name": "Water_ColorTint", "DefaultValue": [1.0, 1.0, 1.0, 1.0]},
    {"Name": "Ground_WearTint", "DefaultValue": [0.7, 0.6, 0.5, 1.0]},
    {"Name": "Fog_ColorTint", "DefaultValue": [0.8, 0.85, 0.9, 1.0]}
  ]
}'''


def generate_niagara_parameters_json() -> str:
    """
    Generate JSON definition for Niagara User Parameters.
    
    These should be added to VDE Niagara systems.
    """
    return '''{
  "Name": "VDE_NiagaraParameters",
  "Parameters": [
    {"Name": "VDE_DustSpawnRate", "Type": "Float", "DefaultValue": 0.0},
    {"Name": "VDE_DustLifetime", "Type": "Float", "DefaultValue": 3.0},
    {"Name": "VDE_DustSizeMin", "Type": "Float", "DefaultValue": 0.5},
    {"Name": "VDE_DustSizeMax", "Type": "Float", "DefaultValue": 2.0},
    {"Name": "VDE_DustVelocityScale", "Type": "Float", "DefaultValue": 1.0},
    {"Name": "VDE_DustColorTint", "Type": "LinearColor", "DefaultValue": [0.8, 0.75, 0.7, 0.3]},
    {"Name": "VDE_PollenSpawnRate", "Type": "Float", "DefaultValue": 0.0},
    {"Name": "VDE_PollenDriftSpeed", "Type": "Float", "DefaultValue": 0.5},
    {"Name": "VDE_PollenSize", "Type": "Float", "DefaultValue": 0.3},
    {"Name": "VDE_DebrisSpawnRate", "Type": "Float", "DefaultValue": 0.0},
    {"Name": "VDE_DebrisFallSpeed", "Type": "Float", "DefaultValue": 1.0},
    {"Name": "VDE_DebrisRotationSpeed", "Type": "Float", "DefaultValue": 1.0},
    {"Name": "VDE_WindDirection", "Type": "Vector", "DefaultValue": [1.0, 0.0, 0.0]},
    {"Name": "VDE_WindDirectionVariance", "Type": "Float", "DefaultValue": 0.0},
    {"Name": "VDE_GlobalVelocityScale", "Type": "Float", "DefaultValue": 1.0},
    {"Name": "VDE_InsectDensity", "Type": "Float", "DefaultValue": 1.0},
    {"Name": "VDE_InsectActivityLevel", "Type": "Float", "DefaultValue": 1.0}
  ]
}'''


if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate VDE UE5 C++ headers')
    parser.add_argument('--output', '-o', default='./ue5_generated',
                       help='Output directory for generated files')
    args = parser.parse_args()
    
    print(f"Generating UE5 headers to {args.output}...")
    generated = generate_all_headers(args.output)
    
    for f in generated:
        print(f"  Generated: {f}")
    
    # Also generate asset definitions
    mpc_path = os.path.join(args.output, 'VDE_Parameters.json')
    with open(mpc_path, 'w') as f:
        f.write(generate_mpc_asset_json())
    print(f"  Generated: {mpc_path}")
    
    niagara_path = os.path.join(args.output, 'VDE_NiagaraParameters.json')
    with open(niagara_path, 'w') as f:
        f.write(generate_niagara_parameters_json())
    print(f"  Generated: {niagara_path}")
    
    print("\nDone!")
